app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// AuthController do Painel
Route::get('login', ['as' => 'panel.login', 'uses' => 'Panel\Auth\AuthController@getLogin']);
Route::post('login', ['as' => 'panel.login', 'uses' => 'Panel\Auth\AuthController@postLogin']);
Route::get('logout', ['as' => 'panel.logout', 'uses' => 'Panel\Auth\AuthController@getLogout']);

// PasswordController do Painel
Route::post('password/email', ['as' => 'panel.password.email', 'uses' => 'Panel\Auth\PasswordController@postEmail']);
Route::get('password/reset/{token}', ['as' => 'panel.reset.token', 'uses' => 'Panel\Auth\PasswordController@getReset']);
Route::post('password/reset', ['as' => 'panel.reset', 'uses' => 'Panel\Auth\PasswordController@postReset']);

// Grupo de Rotas do Painel
Route::group(['middleware' => ['auth'], 'prefix' => '/'], function() {
    // Dashboard
    Route::get('/', ['as' => 'panel', 'uses' => 'Panel\DashboardController@index']);

    // My Profile
    Route::get('profile', ['as' => 'panel.profile', 'uses' => 'Panel\ProfileController@edit']);
    Route::put('profile', ['as' => 'panel.profile', 'uses' => 'Panel\ProfileController@update']);

    // Admin
    Route::group(['middleware' => ['roles'], 'roles' => ['admin'], 'as' => 'panel.admin.'], function() {
        // Users
        Route::resource('users', 'Panel\Admin\UserController', ['except' => ['destroy']]);
    });
});

app/User.php
<?php

namespace App;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

/**
 * User - Eloquent Model
 *
 * @author João Gustavo Balestrin dos Santos <joaogustavo.b@hotmail.com>
 * @copyright (c) 2016
 * @package LaravelPanel
 */
class User extends Model implements AuthenticatableContract,
                                    AuthorizableContract,
                                    CanResetPasswordContract
{
    use Authenticatable, Authorizable, CanResetPassword;

    /**
     * Tabela do banco de dados utilizada pela model
     *
     * @var string
     */
    protected $table = 'users';

    /**
     * Atributos guardados (protegidos)
     *
     * @var array
     */
    protected $guarded = ['role_id'];

    /**
     * Atributos assinaláveis em massa
     *
     * @var array
     */
    protected $fillable = ['name', 'email', 'status'];

    /**
     * Colunas que devem convertidas para um tipo
     *
     * @var array
     */
    protected $casts = [
        'status' => 'boolean',
    ];

    /**
     * Atributo das colunas de data
     *
     * @var array
     */
    protected $dates = ['created_at', 'updated_at'];

    /**
     * Os atributos excluídos no retorno do model
     *
     * @var array
     */
    protected $hidden = ['password', 'remember_token'];

    /**
     * Converte a senha para Bcrypt
     *
     * @param $value
     * @return string
     */
    public function setPasswordAttribute($value)
    {
        // Converte o campo password para Bcrypt
        $this->attributes['password'] = bcrypt($value);
    }

    /**
     * Retorna o grupo que o usuário está relacionado
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function role()
    {
        return $this->hasOne('App\Role', 'id', 'role_id');
    }

    /**
     * Verifica se o usuário pertece ao grupo
     *
     * @param $roles
     * @return bool
     */
    public function hasRole($roles)
    {
        $have_role = $this->getUserRole();

        // Check if the user is a root account
        /*
        if ($have_role->name == 'admin') {
            return true;
        }
        */

        if (is_array($roles)) {
            foreach ($roles as $need_role) {
                if ($this->checkIfUserHasRole($need_role)) {
                    return true;
                }
            }
        } else {
            return $this->checkIfUserHasRole($roles);
        }

        return false;
    }

    /**
     * @return mixed
     */
    private function getUserRole()
    {
        return $this->role()->getResults();
    }

    /**
     * @param $need_role
     * @return bool
     */
    private function checkIfUserHasRole($need_role)
    {
        $have_role = $this->getUserRole();

        return (strtolower($need_role)==strtolower($have_role->name)) ? true : false;
    }
}

app/Http/Controllers/Panel/Admin/UserController.php
<?php

namespace App\Http\Controllers\Panel\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\PanelUserRequest;
use App\Repositories\Contracts\UserRepositoryInterface;
use App\Repositories\Contracts\RoleRepositoryInterface;

/**
 * UserController - Painel Admin
 *
 * @author João Gustavo Balestrin dos Santos <joaogustavo.b@hotmail.com>
 * @copyright (c) 2016
 * @package LaravelPanel
 */
class UserController extends Controller
{
    /**
     * Instancia do UserRepository
     *
     * @var UserRepositoryInterface
     */
    protected $repository;

    /**
     * Instancia do RoleRepository
     *
     * @var UserRepositoryInterface
     */
    protected $roleRepository;

    /**
     * UserController construtor.
     *
     * @param UserRepositoryInterface $repository
     * @param RoleRepositoryInterface $roleRepository
     */
    function __construct(UserRepositoryInterface $repository, RoleRepositoryInterface $roleRepository)
    {
        $this->repository = $repository;
        $this->roleRepository = $roleRepository;
    }

    /**
     * Lista os usuários
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // Busca os usuários mais recentes
        $users = $this->repository->getAllRecent(null);

        // Retorna a view de listar
        return view('panel.admin.user.index', compact('users'));
    }

    /**
     * Retorna a view de cadastrar
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // Busca todos os grupos
        $roles = $this->roleRepository->getAll();

        // Retorna a view de cadastrar
        return view('panel.admin.user.create', compact('roles'));
    }

    /**
     * Insere o usuário na base de dados
     *
     * @param PanelUserRequest $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function store(PanelUserRequest $request)
    {
        // Realiza a inserção na base de dados
        $create = $this->repository->create($request->all());

        // Verifica se a ação foi efetuada com sucesso
        if (!$create) {
            // Retorna uma mensagem de erro
            return response()->json(['type' => 'error', 'msg' => 'Falha no cadastro do usuário', 'redirect' => route('panel.admin.users.index')]);
        }

        // Retorna uma mensagem de sucesso
        return response()->json(['type' => 'success', 'msg' => 'Cadastrado com Sucesso!', 'redirect' => route('panel.admin.users.index')]);
    }

    /**
     * Exibi o usuário encontrado
     *
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show($id)
    {
        // Busca o usuário respectivo pelo ID
        $user = $this->repository->findByID($id);

        // Retorna a view de visualizar
        return view('panel.admin.user.show', compact('user'));
    }

    /**
     * Exibi o formulário de editar
     *
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id)
    {
        // Busca o usuário respectivo pelo ID
        $user = $this->repository->findByID($id);

        // Busca todos os grupos
        $roles = $this->roleRepository->getAll();

        // Retorna a view de editar
        return view('panel.admin.user.edit', compact('user', 'roles'));
    }

    /**
     * Atualiza o usuário na base de dados
     *
     * @param PanelUserRequest $request
     * @param $id
     * @return \Illuminate\Http\JsonResponse
     */
    public function update(PanelUserRequest $request, $id)
    {
        // Busca o usuário respectivo pelo ID
        $user = $this->repository->findByID($id);

        // Captura todos os dados
        $data = $request->all();

        // Verifica se o grupo do usuário é admin e se usuário é diferente do logado
        if ($user->role->name == 'admin' and $user->id != auth()->user()->id) {
            unset($data['password']);
        }

        // Realizar o update no repository
        $update = $this->repository->update($user, $data);

        // Verifica se houve alguma falha no update
        if (!$update) {
            // Retorna uma mensagem de erro
            return response()->json(['type' => 'error', 'msg' => 'Falha na edição do usuário', 'redirect' => route('panel.admin.users.index')]);
        }

        // Retorna uma mensagem de sucesso
        return response()->json(['type' => 'success', 'msg'  => 'Editado com Sucesso!', 'redirect' => route('panel.admin.users.index')]);
    }
}

resources/views/panel/admin/user/create.blade.php
@extends('panel/app')

@section('title', 'Cadastrar Usuário | LaravelPanel')

@section('content')
    <div class="container top_80">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel_mb panel-default">
                    <div class="panel-heading">Cadastrar Usuário</div>

                    <div class="panel-body">
                        <form action="{{ route('panel.admin.users.store') }}" class="form-horizontal ajax-post">
                            <div class="form-group">
                                <label class="col-md-4 control-label" for="name">Nome</label>
                                <div class="col-md-6">
                                    <input type="text" class="form-control" name="name" id="name" required />
                                </div>
                            </div>

                            <div class="form-group mgt_10">
                                <label class="col-md-4 control-label" for="email">E-mail</label>
                                <div class="col-md-6">
                                    <input type="email" class="form-control" name="email" id="email" required />
                                </div>
                            </div>

                            <div class="form-group mgt_10">
                                <label class="col-md-4 control-label">Status</label>
                                <div class="col-md-6">
                                    <div class="radio-list">
                                        <label class="radio-inline"><input type="radio" name="status" value="1" checked>ativo</label>
                                        <label class="radio-inline"><input type="radio" name="status" value="0">inativo</label>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-md-4 control-label">Grupo</label>
                                <div class="col-md-6">
                                    <div class="radio-list">
                                        @foreach($roles as $role)
                                            <label class="radio-inline"><input type="radio" name="role_id" value="{{ $role->id }}" required>{{ $role->display_name }}</label>
                                        @endforeach
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-md-4 control-label" for="password">Senha</label>
                                <div class="col-md-6">
                                    <input type="password" class="form-control" name="password" id="password" required />
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-md-4 control-label" for="password_confirmation">Confirmar Senha</label>
                                <div class="col-md-6">
                                    <input type="password" class="form-control" name="password_confirmation" id="password_confirmation" required />
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-6 col-md-offset-4 btns">
                                    <button type="submit" class="btn btn-success" name="enviarbtn">Cadastrar</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/panel/admin/user/edit.blade.php
@extends('panel/app')

@section('title', 'Editar Usuário | LaravelPanel')

@section('content')
    <div class="container top_80">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel_mb panel-default">
                    <div class="panel-heading">Editar Usuário</div>

                    <div class="panel-body">
                        <form action="{{ route('panel.admin.users.update', [$user->id]) }}" class="form-horizontal ajax-put">
                            <div class="form-group">
                                <label class="col-md-4 control-label" for="name">Nome</label>
                                <div class="col-md-6">
                                    <input type="text" class="form-control" name="name" id="name" value="{{ $user->name }}" required />
                                </div>
                            </div>

                            <div class="form-group mgt_10">
                                <label class="col-md-4 control-label" for="email">E-mail</label>
                                <div class="col-md-6">
                                    <input type="email" class="form-control" name="email" id="email" value="{{ $user->email }}" required>
                                </div>
                            </div>

                            <div class="form-group mgt_10">
                                <label class="col-md-4 control-label">Status</label>
                                <div class="col-md-6">
                                    <div class="radio-list">
                                        <label class="radio-inline"><input type="radio" name="status" value="1" {{ $user->status == 1 ? 'checked' : '' }}>ativo</label>
                                        <label class="radio-inline"><input type="radio" name="status" value="0" {{ $user->status == 0 ? 'checked' : '' }}>inativo</label>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-md-4 control-label">Grupo</label>
                                <div class="col-md-6">
                                    <div class="radio-list">
                                        @foreach($roles as $role)
                                            <label class="radio-inline"><input type="radio" name="role_id" value="{{ $role->id }}" {{ $user->role->id == $role->id ? 'checked' : '' }}>{{ $role->display_name }}</label>
                                        @endforeach
                                    </div>
                                </div>
                            </div>

                            @if($user->role->name != 'admin' or $user->id == auth()->user()->id)
                                <div class="form-group">
                                    <label class="col-md-4 control-label" for="password">Nova Senha</label>
                                    <div class="col-md-6">
                                        <input type="password" class="form-control" name="password" id="password">
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-md-4 control-label" for="password_confirmation">Confirmar Senha</label>
                                    <div class="col-md-6">
                                        <input type="password" class="form-control" name="password_confirmation" id="password_confirmation">
                                    </div>
                                </div>
                            @endif

                            <div class="form-group">
                                <div class="col-md-6 col-md-offset-4 btns">
                                    <button type="submit" class="btn btn-success" name="enviarbtn">Atualizar</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/panel/admin/user/index.blade.php
@extends('panel/app')

@section('title', 'Usuários | LaravelPanel')

@section('content')
    <div class="container top_80">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel_mb panel-default">
                    <div class="panel-heading">Usuários <div class="pull-right"><a href="{{ route('panel.admin.users.create') }}" class="btn btn-success">Cadastrar novo</a></div></div>

                    <div class="panel-body">
                        <table id="dataTable" class="table table-responsive table-striped table-bordered table-hover" cellspacing="0" width="100%">
                            <thead>
                                <tr>
                                    <th>Nome</th>
                                    <th>E-mail</th>
                                    <th>Status</th>
                                    <th>Grupo</th>
                                    <th>Cadastrado em</th>
                                    <th>Ações</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($users as $user)
                                    <tr>
                                        <td class="pt14"><a href="{{ route('panel.admin.users.show', [$user->id]) }}" title="Mais Detalhes">{{ $user->name }}</a></td>
                                        <td class="pt14">{{ $user->email }}</td>
                                        <td class="pt14">
                                            @if($user->status == 1)
                                                <span class="label label-sm label-success">ativo</span>
                                            @else
                                                <span class="label label-sm label-danger">inativo</span>
                                            @endif
                                        </td>
                                        <td class="pt14">{{ $user->role->display_name }}</td>
                                        <td class="pt14">{{ $user->created_at->format('d/m/Y H:i:s') }}</td>
                                        <td>
                                            <a href="{{ route('panel.admin.users.edit', [$user->id]) }}" class="btn btn-sm btn-icon btn-flat btn-default inline-block font15" data-toggle="tooltip" data-original-title="Editar">
                                                <i class="fa fa-pencil" aria-hidden="true"></i>
                                            </a>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/panel/admin/user/show.blade.php
@extends('panel/app')

@section('title', 'Detalhes do Usuário | LaravelPanel')

@section('content')
    <div class="container top_80">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel_mb panel-default">
                    <div class="panel-heading">Detalhes do Usuário</div>

                    <div class="panel-body">
                        <div class="container">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="control-label col-md-3">ID:</label>
                                        <div class="col-md-9">
                                            <p class="form-control-static"> {{ $user->id }} </p>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="control-label col-md-3">Nome:</label>
                                        <div class="col-md-9">
                                            <p class="form-control-static"> {{ $user->name }} </p>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="control-label col-md-3">E-mail:</label>
                                        <div class="col-md-9">
                                            <p class="form-control-static"> {{ $user->email }} </p>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="control-label col-md-3">Status: </label>
                                        <div class="col-md-9">
                                            <p class="form-control-static">
                                                @if($user->status == 1)
                                                    <span class="label label-sm label-success"> ativo </span>
                                                @else
                                                    <span class="label label-sm label-danger"> inativo </span>
                                                @endif
                                            </p>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="control-label col-md-3">Grupo:</label>
                                        <div class="col-md-9">
                                            <p class="form-control-static"> {{ $user->role->display_name }} <span class="blue-tooltip" data-toggle="tooltip" data-placement="right" title="" data-original-title="{{ $user->role->description }}" aria-describedby="tooltip155941"><i class="fa fa-question-circle-o" aria-hidden="true"></i></span></p>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="control-label col-md-3">Cadastrado em:</label>
                                        <div class="col-md-9">
                                            <p class="form-control-static"> {{ $user->created_at->format('d/m/Y H:i:s') }} </p>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="control-label col-md-3">Atualizado em:</label>
                                        <div class="col-md-9">
                                            <p class="form-control-static"> {{ $user->updated_at->format('d/m/Y H:i:s') }} </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection